package com.dentinium.hibernate;
// Generated May 9, 2015 1:08:47 AM by Hibernate Tools 4.3.1



/**
 * Admins generated by hbm2java
 */
public class Admins  implements java.io.Serializable {


     private int adminid;
     private Users user;
     
    public Admins() {
    }

	
    public Admins(int adminid, Users user) {
        this.adminid = adminid;
        this.user = user;
    }

    public int getAdminid() {
        return this.adminid;
    }
    
    public void setAdminid(int adminid) {
        this.adminid = adminid;
    }

    /**
     * @return the user
     */
    public Users getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(Users user) {
        this.user = user;
    }




}


