package com.dentinium.hibernate;
// Generated May 9, 2015 1:08:47 AM by Hibernate Tools 4.3.1

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

    private int companyid;
    private String companyname;
    private String address;
    private String phone;
    private Users user;

    public Company() {

    }

    public Company(int companyid, Users user, String companyname) {
        this.companyid = companyid;
        this.companyname = companyname;
        this.user = user;

    }

    public Company(int companyid, Users user, String companyname, String phone, String address) {
        this.companyid = companyid;
        this.companyname = companyname;
        this.user = user;
        this.phone = phone;
        this.address = address;
    }

    public int getCompanyid() {
        return this.companyid;
    }

    public void setCompanyid(int companyid) {
        this.companyid = companyid;
    }

    public String getCompanyname() {
        return this.companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * @return the address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * @return the phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * @param phone the phone to set
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * @return the user
     */
    public Users getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(Users user) {
        this.user = user;
    }

}
