package com.dentinium.hibernate;
// Generated May 9, 2015 1:08:47 AM by Hibernate Tools 4.3.1

import com.dentinium.customer.UserDataController;


/**
 * Doctors generated by hbm2java
 */
public class Doctors implements java.io.Serializable {

    private int doctorid;

    private Company company;
    private Users user;


    public Doctors() {
  
    }
    public Doctors(int doctorid, Company company, Users user) {
        this.doctorid = doctorid;
        this.user = user;
        this.company = company;
    }


    public int getDoctorid() {
        return this.doctorid;
    }

    public void setDoctorid(int doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * @return the company
     */
    public Company getCompany() {
        return company;
    }

    /**
     * @param company the company to set
     */
    public void setCompany(Company company) {
        this.company = company;
    }

    /**
     * @return the user
     */
    public Users getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(Users user) {
        this.user = user;
    }
    
    public String getName()
    {
       UserDataController controller = new UserDataController();
       
      Users user = controller.getUserByID(doctorid);
               return user.getName();
    }


}
