package com.dentinium.hibernate;
// Generated May 9, 2015 1:08:47 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Reservations generated by hbm2java
 */
public class Reservations implements java.io.Serializable {

    private int reservationid;
    private Date date;
    private int cost;
    
    private Users user;
    private Doctors doctor;
    private Rooms room;
    private Company company;
    
    
    public Reservations() {

    }

    public Reservations(int reservationid, Date date, Users user, Doctors doctor, Rooms room, Company company, int cost) {
        this.reservationid = reservationid;
        this.user = user;
        this.doctor = doctor;
        this.room = room;
        this.date = date;
        this.company = company;
        this.cost = cost;

    }

    public Reservations(int reservationid, Date date, Doctors doctor, Rooms room, Company company, int cost) {
        this.reservationid = reservationid;
        this.doctor = doctor;
        this.room = room;
        this.date = date;
        this.company = company;
        this.cost = cost;

    }

    public Reservations(int reservationid, Date date, Doctors doctor, Rooms room,Company company) {
        this.reservationid = reservationid;
        this.doctor = doctor;
        this.room = room;
        this.company = company;
        this.date = date;
    }

    public int getReservationid() {
        return this.reservationid;
    }

    public void setReservationid(int reservationid) {
        this.reservationid = reservationid;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public int getCost() {
        return this.cost;
    }

    public void setCost(int cost) {
        this.cost = cost;
    }

    /**
     * @return the customer
     */
    public Users getUser() {
        return user;
    }

    /**
     * @param customer the customer to set
     */
    public void setUser(Users user) {
        this.user = user;
    }

    /**
     * @return the doctor
     */
    public Doctors getDoctor() {
        return doctor;
    }

    /**
     * @param doctor the doctor to set
     */
    public void setDoctor(Doctors doctor) {
        this.doctor = doctor;
    }

    /**
     * @return the room
     */
    public Rooms getRoom() {
        return room;
    }

    /**
     * @param room the room to set
     */
    public void setRoom(Rooms room) {
        this.room = room;
    }

    /**
     * @return the company
     */
    public Company getCompany() {
        return company;
    }

    /**
     * @param company the company to set
     */
    public void setCompany(Company company) {
        this.company = company;
    }

}
