package com.dentinium.hibernate;
// Generated May 9, 2015 1:08:47 AM by Hibernate Tools 4.3.1



/**
 * Rooms generated by hbm2java
 */
public class Rooms  implements java.io.Serializable {


     private int roomid;
     private String roomname;
     private Doctors doctor;
     
    public Rooms() {
    }


    public Rooms(int roomid, String roomname,Doctors doctor) {
       this.roomid = roomid;
       this.roomname = roomname;
       this.doctor = doctor;
    }
   
    public int getRoomid() {
        return this.roomid;
    }
    
    public void setRoomid(int roomid) {
        this.roomid = roomid;
    }
    public String getRoomname() {
        return this.roomname;
    }
    
    public void setRoomname(String roomname) {
        this.roomname = roomname;
    }

    /**
     * @return the doctor
     */
    public Doctors getDoctor() {
        return doctor;
    }

    /**
     * @param doctor the doctor to set
     */
    public void setDoctor(Doctors doctor) {
        this.doctor = doctor;
    }

    
    public String toString()
    {
        return this.roomname;
    }
}


