package com.dentinium.hibernate;
// Generated May 9, 2015 1:08:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userid;
     private String username;
     private String token;
     private Date lastlogin;
     private Date date;
     private String phone;
     private String email;
     private String address;
     private String name;
     private String password;

    public Users() {
    }

	
    public Users(int userid, String username,String password, String email, String name) {
        this.userid = userid;
        this.username = username;
        this.email = email;
        this.name = name;
        this.password= password;
    }
    
     public Users(int userid, String username, String password, String token, Date date, String phone, String email, String address, String name) {
       this.userid = userid;
       this.username = username;
       this.token = token;

       this.date = date;
       this.phone = phone;
       this.email = email;
       this.password = password;
       this.address = address;
       this.name = name;
    }
     
    public Users(int userid, String username, String password, String token, Date lastlogin, Date date, String phone, String email, String address, String name) {
       this.userid = userid;
       this.username = username;
       this.token = token;
       this.lastlogin = lastlogin;
       this.date = date;
       this.phone = phone;
       this.email = email;
       this.password = password;
       this.address = address;
       this.name = name;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


